In [1]:
import pandas as pd
import sklearn
import numpy as np
df = pd.read_csv('svm-data.csv' , header=None)

In [2]:
df

0     1     2
0  0.0  0.70  0.29
1  1.0  0.23  0.55
2  0.0  0.72  0.42
3  0.0  0.98  0.68
4  0.0  0.48  0.39
5  1.0  0.34  0.73
6  0.0  0.44  0.06
7  1.0  0.40  0.74
8  0.0  0.18  0.18
9  1.0  0.53  0.53

In [3]:
Y = df[0]
X = df.drop(0, axis=1) 



In [4]:
from sklearn.svm import SVC
svm=SVC(kernel='linear',C=100000, random_state=241 )

In [5]:
svm.fit(X, Y)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=241,
  shrinking=True, tol=0.001, verbose=False)

In [6]:
print(svm.support_)

[3 4 9]


In [7]:
from sklearn import datasets

newsgroups = datasets.fetch_20newsgroups(
                    subset='all', 
                    categories=['alt.atheism', 'sci.space']
             )

In [8]:
svd = pd.read_csv('train.csv')

In [9]:
svd.head()

ID        Ra        Rb        Ga        Gb        Ba        Bb  Class
0   0  0.805265  0.363115  0.856093  0.435039  0.774563  0.351019      0
1   1  0.814729  0.388415  0.837164  0.494050  0.833725  0.385560      0
2  32  0.800147  0.390153  0.755200  0.414155  0.807923  0.369876      0
3  33  1.047313  0.463262  1.101706  0.541262  1.069398  0.451768      0
4   2  0.908248  0.411242  1.111793  0.747647  0.906309  0.439232      0

In [10]:
svd['Class'].value_counts()

0    100
1     25
2     23
Name: Class, dtype: int64

In [11]:
YY=svd['Class']
XX=svd.drop(['Class'], axis='columns')
XX=XX.drop(['ID'], axis='columns')

In [12]:
svm.fit(XX, YY)

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=241,
  shrinking=True, tol=0.001, verbose=False)

In [13]:
print(svm.support_)

[ 24  28  36  53 100 101 112 136 140 142]


In [14]:
svd_test = pd.read_csv('test.csv', index_col='ID')
svd_test= svd_test.sort_index()
svd_test.head()

Ra        Rb        Ga        Gb        Ba        Bb
ID                                                            
0   0.805265  0.363115  0.856093  0.435039  0.774563  0.351019
1   0.814729  0.388415  0.837164  0.494050  0.833725  0.385560
2   0.908248  0.411242  1.111793  0.747647  0.906309  0.439232
3   1.028690  0.428797  1.042374  0.548634  1.086771  0.450598
4   0.996097  0.463845  1.125580  0.605383  0.948803  0.475941

In [15]:
Xt=svd_test

In [16]:
ys=svm.predict(Xt)

In [17]:
ys

array([0, 0, 0, ..., 0, 2, 1], dtype=int64)

In [18]:
f = open('prdct.txt', 'w')

In [19]:
np.savetxt(f, ys, fmt = '%d',newline=' ' )

In [20]:
f.close()



In [21]:
import sklearn
from sklearn.model_selection import LeaveOneOut
loo = LeaveOneOut()
from sklearn.model_selection import KFold
kf = KFold(n_splits=1024, shuffle=True, random_state=42)


acc=sklearn.model_selection.cross_val_score(X=XX,y=YY, cv=loo,estimator =svm)


In [22]:
acc.mean()

0.9662162162162162

In [23]:
from sklearn.neighbors import KNeighborsClassifier
t=[]
for k in range(1,51):
    knn = KNeighborsClassifier(n_neighbors=k)
    acc=sklearn.model_selection.cross_val_score(X=XX,y=YY, cv=loo,estimator =knn)
    t.append(acc.mean())

In [24]:
k_best=t.index(max(t))+1
k_best_accuracy=max(t)
print (k_best_accuracy ,k_best)

0.9864864864864865 1


In [25]:
m=[]
p=[]
for l in np.linspace(1,10,200):
    knn = KNeighborsClassifier(n_neighbors=1, weights='distance', p=l)
    acc=sklearn.model_selection.cross_val_score(X=XX,y=YY, cv=loo,estimator =knn)
    m.append(acc.mean())
    p.append(l)

In [26]:
p_best=p[m.index(max(m))]
p_best_accuracy=max(m)
print (p_best_accuracy ,p_best)

0.9864864864864865 1.0


In [40]:
k= KNeighborsClassifier(n_neighbors=1, weights='distance', p=1)
y_knn=svm.predict(Xt)

In [41]:
d = open('prdct_knn.txt', 'w')

In [42]:
np.savetxt(d, ys, fmt = '%d',newline=' ' )

In [ ]:
d.close()

In [34]:
mn=m.index(max(m))
pi=p[mn]


In [35]:
pi

1.0